# Generated by Django 5.2.5 on 2025-08-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threatdetection',
            old_name='scan_name',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='threatdetection',
            old_name='created_at',
            new_name='scanned_at',
        ),
        migrations.RemoveField(
            model_name='threatdetection',
            name='result',
        ),
        migrations.RemoveField(
            model_name='threatdetection',
            name='scan_data',
        ),
        migrations.AddField(
            model_name='threatdetection',
            name='confidence',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='threatdetection',
            name='detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='threatdetection',
            name='threat_type',
            field=models.CharField(default=0.0, max_length=100),
            preserve_default=False,
        ),
    ]
