# Generated by Django 5.2.5 on 2025-08-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_rename_scan_name_threatdetection_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatdetection',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='threatdetection',
            name='threat_type',
            field=models.CharField(max_length=255),
        ),
    ]
