# Generated by Django 5.2.5 on 2025-09-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_threatdetection_uploaded_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatdetection',
            name='explanation',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='threatdetection',
            name='threat_type',
            field=models.CharField(max_length=100),
        ),
    ]
