# Generated by Django 5.2.5 on 2025-09-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_threatdetection_explanation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatdetection',
            name='explanation',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
