# Generated by Django 5.2.5 on 2025-09-18 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_alter_threatdetection_explanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.threatdetection')),
            ],
        ),
    ]
