# Generated by Django 5.2.5 on 2025-09-18 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0006_reportemaillog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportemaillog',
            old_name='email',
            new_name='recipient_email',
        ),
    ]
