# Generated by Django 5.2.5 on 2025-09-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0007_rename_email_reportemaillog_recipient_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVEClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('label', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('classified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
