# Generated by Django 5.2.5 on 2025-09-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0008_cveclassification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cveclassification',
            old_name='text',
            new_name='input_text',
        ),
        migrations.AddField(
            model_name='cveclassification',
            name='keywords',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
