# Generated by Django 5.2.5 on 2025-12-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0009_rename_text_cveclassification_input_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVEClassifyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('engine_response', models.JSONField(blank=True, default=dict)),
                ('classified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CVEClassification',
        ),
        migrations.RemoveField(
            model_name='threatdetection',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='threatdetection',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='threatdetection',
            name='threat_type',
        ),
        migrations.AddField(
            model_name='threatdetection',
            name='engine_response',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
