# Generated by Django 5.2.5 on 2025-12-19 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0010_cveclassifyresult_delete_cveclassification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cveclassifyresult',
            options={'ordering': ['-classified_at']},
        ),
        migrations.AlterModelOptions(
            name='reportemaillog',
            options={'ordering': ['-sent_at']},
        ),
        migrations.AlterModelOptions(
            name='threatdetection',
            options={'ordering': ['-scanned_at']},
        ),
        migrations.RemoveField(
            model_name='threatdetection',
            name='uploaded_file',
        ),
        migrations.AlterField(
            model_name='reportemaillog',
            name='detection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='detection.threatdetection'),
        ),
        migrations.AddIndex(
            model_name='threatdetection',
            index=models.Index(fields=['detected'], name='detection_t_detecte_ff45b3_idx'),
        ),
        migrations.AddIndex(
            model_name='threatdetection',
            index=models.Index(fields=['scanned_at'], name='detection_t_scanned_f0e520_idx'),
        ),
    ]
